###This is for the Orcale java###
sudo apt-add-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer

####This is for Eclipse CDT ########
sudo apt-get install eclipse eclipse-cdt

#####For Sublime 3 ###############
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer

##### This is for Kdevelop ####
sudo apt-get install kdevelop
